name: layoutdetr
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.10
  - pip=22.3.1
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - pip:
    - numpy=1.19.2
    - torch-geometric==2.0.3
    - torch-utils==0.1.2
    - torchfile==0.1.0
    - torchgeometry==0.1.2
    - torchmetrics==0.2.0
    - transformers==4.19.2
    - pytorch-fid==0.2.1
    - click==8.0.3
    - seaborn==0.11.2
    - selenium==4.4.3
    - timm==0.5.4
    - fairscale==0.4.5
    - psutil==5.8.0
    - beautifulsoup4==4.11.1
    - imageio==2.13.1
    - imageio-ffmpeg==0.4.6
    - tensorboardX==2.5.1
    - cython==0.29.24
    - mujoco-py==1.50.1.56
    - mpi4py==3.0.0
    - ipdb
    - glfw
    - pylint
    - tqdm==4.62.3
    - autopep8
    - pyyaml==6.0
    - fuzzywuzzy
    - python-Levenshtein
    - stanford-corenlp
    - pytorch-pretrained-BERT
    - matplotlib==3.5.0
    - scipy==1.6.3
    - scikit-learn==0.24.2
    - Pillow==9.3.0
    - h5py==3.6.0
    - lmdb==1.2.1
    - opencv-python==4.6.0.66
    - requests==2.26.0
    - cryptography==3.3.2
    - six==1.16.0
    - scikit-image==0.17.2
    - boto3